
version: '3'

services:
  couchserver:
    image: couchdb
    restart: always
    ports:
    - "5984:5984"
    environment:
    - COUCHDB_USER=admin
    - COUCHDB_PASSWORD=YOURPASSWORD
    volumes:
    - ./dbdata:/opt/couchdb/data
  
  client1:
    image: nginx
    ports:
    - '8081:80'
    depends_on:
    - couchserver
    volumes:
    - ./client:/usr/share/nginx/html
  
  client2:
    image: nginx
    ports:
    - '8082:80'
    depends_on:
    - couchserver
    volumes:
    - ./client:/usr/share/nginx/html

  client3:
    image: nginx
    ports:
    - '8083:80'
    depends_on:
    - couchserver
    volumes:
    - ./client:/usr/share/nginx/html